pipeline:
  name: test-main-fearture
  identifier: testmainfearture
  projectIdentifier: gitxtest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: d-v
        identifier: dv
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: mainbranchsvc
          environment:
            environmentRef: mainbranchenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: mainbranchinfra
          execution:
            steps:
              - step:
                  type: Verify
                  name: Verify_1
                  identifier: Verify_1
                  spec:
                    isMultiServicesOrEnvs: false
                    type: Rolling
                    monitoredService:
                      type: Template
                      spec:
                        branch: test-run
                        monitoredServiceTemplateRef: account.remotemts
                        versionLabel: v1
                        templateInputs: {}
                        monitoredServiceTemplateGitBranch: main
                    spec:
                      sensitivity: HIGH
                      duration: 5m
                  timeout: 2h
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Verification
                        action:
                          type: ManualIntervention
                          spec:
                            timeout: 2h
                            onTimeout:
                              action:
                                type: StageRollback
                    - onFailure:
                        errors:
                          - Unknown
                        action:
                          type: ManualIntervention
                          spec:
                            timeout: 2h
                            onTimeout:
                              action:
                                type: Ignore
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
