pipeline:
  name: Org-Remote-test
  identifier: OrgRemotetest
  projectIdentifier: CV_Sanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: d-v-01
        identifier: dv01
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: org.orgremotesvc
          environment:
            environmentRef: remoteenvffon
            deployToAll: false
            infrastructureDefinitions:
              - identifier: remoteinfraffon
          execution:
            steps:
              - step:
                  type: Verify
                  name: AIVerifyV1_1
                  identifier: AIVerifyV1_1
                  spec:
                    isMultiServicesOrEnvs: false
                    type: Rolling
                    monitoredService:
                      type: Template
                      spec:
                        monitoredServiceTemplateRef: org.testremotev1org
                        versionLabel: v1
                        templateInputs: {}
                        monitoredServiceTemplateGitBranch: main
                    spec:
                      sensitivity: HIGH
                      duration: 5m
                  timeout: 2h
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Verification
                        action:
                          type: ManualIntervention
                          spec:
                            timeout: 2h
                            onTimeout:
                              action:
                                type: StageRollback
                    - onFailure:
                        errors:
                          - Unknown
                        action:
                          type: ManualIntervention
                          spec:
                            timeout: 2h
                            onTimeout:
                              action:
                                type: Ignore
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
