apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cv-prometheus
  labels:
    app: {{ .Release.Name }}-cv-prometheus
    harness.io/release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cv-prometheus
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cv-prometheus
        harness.io/release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: {{ .Values.prometheus.scrape | quote }}
        prometheus.io/path: {{ .Values.prometheus.path | quote }}
        prometheus.io/port: {{ .Values.prometheus.port | quote }}
    spec:
      containers:
        - name: cv-prometheus
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
